package Dispositivi;

public enum Operazione {
    AGGIUNGI_AL_CARRELLO,
    RIMUOVI_DAL_CARRELLO,
    VERIFICA_ID_NEL_CARRELLO,
    VERIFICA_CARRELLO_VUOTO,
    CERCA_PRODOTTO_NEL_CARRELLO,
    CALCOLA_PREZZO_FINALE,
    SVUOTA_CARRELLO,
    STAMPA_ELEMENTI_CARRELLO,
    AGGIUNGI_AL_MAGAZZINO,
    STAMPA_ELEMENTI_MAGAZZINO
}
